version: "3.2"
services:
 web:
    container_name: "web${web_version}"
    image: "web:v${web_version}"
    privileged: true
    tty: true
    ports:
      - "${APP_PORT}:80"
      - "${APP_PORT_SSL}:443"
      #- "3000:3000" # phpmyadmmin ports value
      #- "33066:3306" # mysql ports value
    volumes:
      - ./web/nginx/:/usr/local/openresty/nginx/
      - ./mysqlbak/:/etc/mysql/bak/
      - ./web/mysql/:/var/lib/mysql/
      - ./web/etc/:/etc/
      - ./web/phpmyadmin/:/usr/local/phpmyadmin/
    environment:
      TZ: "Asia/Shanghai"
    restart: unless-stopped
